# Generated by Django 4.0.5 on 2022-06-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='Hobby_Icons')),
                ('name', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=60)),
                ('company', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('desktop_image', models.ImageField(help_text='1920x1080', upload_to='wallpaper')),
                ('mobile_image', models.ImageField(help_text='640x1145', upload_to='wallpaper')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=100)),
                ('number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=40)),
                ('whatsapp', models.CharField(max_length=50)),
                ('telegram', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OtherExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poem', models.TextField(max_length=600, unique=True)),
                ('who_said', models.CharField(max_length=30)),
                ('poem_type', models.CharField(default='رباعی', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('percentage', models.IntegerField()),
            ],
        ),
    ]
