# Generated by Django 4.0.5 on 2022-06-03 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hobby',
        ),
        migrations.RemoveField(
            model_name='homepageinfo',
            name='desktop_image',
        ),
        migrations.RemoveField(
            model_name='homepageinfo',
            name='mobile_image',
        ),
    ]
