# Generated by Django 4.0.5 on 2022-06-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('body', models.TextField(max_length=500)),
                ('preview_body', models.TextField(max_length=50)),
                ('image', models.ImageField(upload_to='templates_images')),
                ('file', models.FileField(upload_to='Templates_files')),
            ],
        ),
    ]
