# Generated by Django 4.0.5 on 2022-06-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('single_post_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='bg_music',
            field=models.FileField(default=1, upload_to='BgMusics'),
            preserve_default=False,
        ),
    ]
