# Generated by Django 4.0.5 on 2022-06-04 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('single_post_app', '0002_story_bg_music'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='bg_music',
        ),
    ]
